
defaults:
  run:
    working-directory: web
name: Node.js CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
<<<<<<< HEAD
    - run: npm run test:headless
    - run: sh ./scripts/e2e.sh
=======
    - run: npx ng serve &
    - run: npx wait-on http://localhost:4200 && cd e2e
    - run: npx webdriver-manager update
    - run: npx protractor protractor.conf.js
>>>>>>> 209feb5aec7f6a02c441d32a126a146618dc6547
      
